spring.application.name=library-management-system
spring.datasource.url=jdbc:mysql://localhost:3306/library_management

spring.datasource.username=root

spring.datasource.password=Suguu@2906

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
server.port=8081